### ISSUE TITLE
Deserialize into a fixed-size array

### ISSUE THREAD

**Issue by dtolnay** [KokaKiwi/rust-hex#10]
Feedback from https://github.com/shssoichiro/avsser/issues/2#issuecomment-299645567:

> I will say I wish that the `hex` crate could deserialize into a fixed-size array, like `rustc-serialize` could. I found a better way to do it in this crate (because the hex strings were UUIDs), but it would still be a good functionality to have.

**Comment by LukasKalbertodt** [comment]
Added in #11 (for arrays up to size 16, but that can easily be extended)

**Comment by zrkn** [comment]
Any plans for releasing it to crates.io?

**Comment by KokaKiwi** [comment]
I'm thinking about publishing a `0.3.0` version in crates.io with the current changes, and publishing a `0.3.1` with #13, which seems to me to be a sufficiently good way to do this thing

**Comment by KokaKiwi** [comment]
I published a `0.3.0` version with latest changes (minus #13), so I'm closing this issue
