### ISSUE TITLE
Git tags for releases

### ISSUE THREAD

**Issue by Nemo157** [KokaKiwi/rust-hex#26]
It would be really nice if you could tag the commits that are used for releases, that would make it really easy for tools like Dependabot to link to which commits are included in a new release when evaluating an update PR.

**Comment by Nemo157** [comment]
(Relatedly the version number on master doesn't appear to have been bumped for 0.4.0)

**Comment by KokaKiwi** [comment]
Uh forgot to push here >< (I have this repo and another one on my GitLab instance, and i sometimes mess up with them...)
Will do that soon, I should take the habit to tag every release

**Comment by KokaKiwi** [comment]
Done :smile:

**Comment by Nemo157** [comment]
:tada: thanks a lot for back filling the old releases as well!
