### ISSUE TITLE
A couple ideas, both breaking changes

### ISSUE THREAD

**Issue by frewsxcv** [KokaKiwi/rust-hex#4]
#### Update `FromHex::from_hex` to accept `&[u8]` instead of `&str`.

It seems to be overkill to pass unicode into a function that operates on ASCII bits. The first operation that happens is [converting the unicode to bytes](https://github.com/KokaKiwi/rust-hex/blob/eb3db11f9f8c7a54cf245b1a3524b6ae8f5df615/src/lib.rs#L72) anyways. Consider a couple scenarios:

Current design:

```rust
Vec::from_hex("hello")
Vec::from_hex(str::from_utf8(b"hello").unwrap())
```

With my proposal:

```rust
Vec::from_hex("hello".as_bytes())
Vec::from_hex(b"hello")
```

#### Stop [accepting whitespace](https://github.com/KokaKiwi/rust-hex/blob/eb3db11f9f8c7a54cf245b1a3524b6ae8f5df615/src/lib.rs#L79) in the input to `FromHex::from_hex`

Is there any reason for this? I feel like if the user passes in superfluous characters that are not hex to `from_hex`, it should probably be result in an error.

Thoughts?

**Comment by frewsxcv** [comment]
I can make these changes if you think they're worth changing.

**Comment by KokaKiwi** [comment]
> Update FromHex::from_hex to accept &[u8] instead of &str

Why not simply make `FromHex::from_hex` accept an argument of type `S: AsRef<[u8]>` which would allow both cases?

> Stop accepting whitespace in the input to FromHex::from_hex

I don't really know, as accepting whitespace doesn't seem to have big drawbacks to me (regarding performances), but it doesn't feel right either now that you mentioned this.

In fact I don't really know the reasons for accepting whitespaces as it was already here where I extracted this code from the `rustc-serialize` crate (and seems to be [still there](https://github.com/rust-lang-nursery/rustc-serialize/blob/master/src/hex.rs#L134))

PS: As it seems that "1234 5678".parse() doesn't accept either whitespaces, maybe it would be alright to result in an error too indeed.

**Comment by frewsxcv** [comment]
Thanks!
