### ISSUE TITLE
Attribute "The Rust Project Developers" ?

### ISSUE THREAD

**Issue by frewsxcv** [KokaKiwi/rust-hex#7]
https://github.com/KokaKiwi/rust-hex/commit/2cbeff7c33c9a80923beffe858d91b5fa9072944

https://github.com/rust-lang/rust/blob/master/src/libserialize/hex.rs

It looks like this project is based on `hex.rs` from the compiler. Shouldn't this project retain the license headers and copyright for rust-lang/rust?

**Comment by KokaKiwi** [comment]
As I did some modifications on the original code, I was thinking the correct thing to do is having both `The Rust Project Developers` and `The rust-hex Developers` copyright notices.

I'll commit something with the modifications tomorrow I think (it's night here)

**Comment by frewsxcv** [comment]
:+1:
